### PR TITLE
PMM-3000 update use case for monitoring rds postgre sql

### PR DESCRIPTION
**Pull request by fiowro**

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-223/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-223/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-223/

**Comment by michaelcoburn** [comment]
On use-case.external-monitoring-service.postgresql.rds.rst, please add:
- example needs to be pmm-admin add postgresql .  Currently the example is pmm-admin list
- Change last section to not reference Advanced Data Exploration, but instead mention PostgreSQL Overview dashboard. Also clean up sentences so that they relate to the PG Dashboard.

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-223/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-223/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-223/

**Comment by michaelcoburn** [comment]
Fixes:
- "by pmm-admin add postgresql" - should be:  pmm-admin add postgresql --host=10.10.10.10 --password=ABC123 --user=pmm
- instruction should be instructions
- include images for PMM menu PG and also main dropdown Grafana menu system 
image

**Comment by michaelcoburn** [comment]
lgtm

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-223/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-223/

**Pull request merged**
