### PR TITLE
PMM-4949 RDS Management API.

### PR DESCRIPTION
**Pull request by AlekSi**
https://github.com/Percona-Lab/pmm-submodules/pull/552

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-466/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-466/

**Comment by AlekSi** [comment]
@BupycHuk PTAL

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-466/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-466/

**Pull request merged**
