### PR TITLE
PMM-2823 fix - change autogenerated glossary into the options list to…

### PR DESCRIPTION
**Pull request by AlekSi**
… have visible anchors

Please merge it or delete this branch.

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Comment by AlekSi** [comment]
There is a merge conflict, please resolve it.

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-281/

**Pull request merged**
