### PR TITLE
PMM-4425 Auth error.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-404/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-404/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-404/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-404/

**Comment by AlekSi** [comment]
@BupycHuk PTAL

**Pull request merged**
