### PR TITLE
PMM-2879 (subtask PMM-2883) documenting simplified PMM installation v…

### PR DESCRIPTION
**Pull request by fiowro**
…ia get-pmm.sh

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-229/

**Comment by michaelcoburn** [comment]
English content is fine

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-229/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-229/

**Pull request merged**
