### PR TITLE
binary shift for iota

### PR DESCRIPTION
**Pull request by OrlovEvgeny**
as title.

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=503) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=503) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm?pullRequest=503) it.</sub>

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-503/

**Comment by AlekSi** [comment]
Please check https://github.com/percona/pmm/blob/PMM-2.0/README.md. The `master` branch contains code for 1.x.

**Comment by OrlovEvgeny** [comment]
oh, ok. I think that this pr to close.

**Pull request closed without merging**
