### PR TITLE
Fix IA migration script

### PR DESCRIPTION
**Pull request by artemgavrilov**
PMM-0

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

### CODE REVIEW

**Review by oksana-grishchenko — APPROVED** [review]

**Comment by PavelKhripkov** [comment]
This will wrap `expr` recursively. Is it what we want? https://github.com/percona/pmm/blob/4076a3f08f2ecbc1a668e71d906c7aeb0f332b92/ia_migration.py#L43

**Comment by artemgavrilov** [comment]
> This will wrap `expr` recursively. Is it what we want?
> 
> https://github.com/percona/pmm/blob/4076a3f08f2ecbc1a668e71d906c7aeb0f332b92/ia_migration.py#L43

Yes,  we are using VM filter function here, and it can handle only one KV pair at once. So if we have multiple filters we should wrap original expression multiple times

https://docs.victoriametrics.com/MetricsQL.html#label_match

**Review by PavelKhripkov — APPROVED** [review]

**Comment by PavelKhripkov** [comment]
@artemgavrilov do we need license header in the migration script?

**Comment by artemgavrilov** [comment]
> @artemgavrilov do we need license header in the migration script?

I don't know, but added)

**Review by BupycHuk — APPROVED** [review]

**Review by gen1us2k — APPROVED** [review]

**Pull request merged**
