### PR TITLE
PMM-10285 fix swagger CVE

### PR DESCRIPTION
**Pull request by BupycHuk**
PMM-10285

Build: SUBMODULES-2631

- [ ] https://github.com/percona/pmm-update/pull/222

### CODE REVIEW

**Review by gen1us2k — APPROVED** [review]

**Comment by artemgavrilov** [comment]
@BupycHuk How did you update these files?

**Comment by BupycHuk** [comment]
@artemgavrilov copy-paste from dists :)

**Comment by artemgavrilov** [comment]
> @artemgavrilov copy-paste from dists :)

Can we create makefile target for that? It looks like we can.

**Review by ademidoff — APPROVED** [review]

**Comment by BupycHuk** [comment]
@artemgavrilov let's do it in a separate PR. This one needs to be in 2.29.

**Comment by artemgavrilov** [comment]
> @artemgavrilov let's do it in a separate PR. This one needs to be in 2.29.

Yep, sure

**Pull request merged**
