### PR TITLE
MySQL 5.6 removed from AWS

### PR DESCRIPTION
**Pull request by rikwasmus**
[PMM-11853](https://jira.percona.com/browse/PMM-11853)

Remove aurora as engine type, only aurora-mysql is now supported for aurora mysql flavors.

MySQL  5.6 is no longer supported
`aws rds describe-db-engine-versions --engine aurora`  has started failing in eu-west-1 and eu-central-1 regions.

### CODE REVIEW

**Comment by rikwasmus** [comment]
FWIW: API now returns "An error occurred (InvalidParameterValue) when calling the DescribeDBEngineVersions operation: Unrecognized engine name: aurora"

**Comment by artemgavrilov** [comment]
Hi @rikwasmus! Thank you for your contribution. Can you please rebase your PR and make it consist only of your commits?

**Comment by BupycHuk** [comment]
Hi @rikwasmus thank you for the contribution, we will appreciate it if you can do it before the 6th of April, so we will be able to include it in the next release.

**Comment by BupycHuk** [comment]
Hi, @rikwasmus I rebased your commits from your PR to https://github.com/percona/pmm/pull/1955 and we merged them. Thank you for your contribution

**Comment by Aleksa-del** [comment]
Hi, @rikwasmus ! Thank you for your contributions. We would like to send you a gift to reward you. Please, contact us at community-team@percona.com.

**Pull request merged**
