### PR TITLE
PMM-12175 fix FB for EL7.

### PR DESCRIPTION
**Pull request by BupycHuk**
PMM-12175

Link to the Feature Build: SUBMODULES-3300

If this PR adds or removes or alters one or more API endpoints, please review and add or update the relevant [API documents](https://github.com/percona/pmm/tree/main/docs/api) as well:

- [ ] API Docs updated

If this PR is related to some other PRs in this or other repositories, please provide links to those PRs:

- Links to related pull requests (optional).

### CODE REVIEW

**Review by atymchuk — APPROVED** [review]

**Comment by atymchuk** [comment]
@BupycHuk Those pipelines will fail until we fix the `301 Commands should not change things if nothing needs doing` issue. Let's add `changed_when: false` to make it pass.

**Comment by BupycHuk** [comment]
@atymchuk those pipelines are failing not because of this change, but because of #2253

**Comment by atymchuk** [comment]
> @atymchuk those pipelines are failing not because of this change, but because of #2253

I'm well aware about the source, I was just looking for a fix :)

**Comment by JiriCtvrtka** [comment]
Since its merged I tested it just now and for me it persist same, is there anything from Talha need for this?

**Pull request merged**
