### PR TITLE
PMM-12338 Remove forced colors in logger.

### PR DESCRIPTION
**Pull request by JiriCtvrtka**
PMM-12338

Link to the Feature Build: SUBMODULES-0

If this PR adds or removes or alters one or more API endpoints, please review and add or update the relevant [API documents](https://github.com/percona/pmm/tree/main/docs/api) as well:

- [ ] API Docs updated

If this PR is related to some other PRs in this or other repositories, please provide links to those PRs:

- Links to related pull requests (optional).

### CODE REVIEW

**Comment by BupycHuk** [comment]
what do you think if we move all of this to `utils` directory to not have duplication?

**Comment by JiriCtvrtka** [comment]
@BupycHuk Sounds like a great idea. Ok I will do it.

**Review by atymchuk — APPROVED** [review]

**Comment by JiriCtvrtka** [comment]
@BupycHuk I checked it and we dont have root folder utils in PMM repo. Does it makes sense to place it into managed utils and then couple it by using it anywhere else?

**Review by artemgavrilov — APPROVED** [review]

**Comment by JiriCtvrtka** [comment]
PR with root utils folder: https://github.com/percona/pmm/pull/2399

**Comment by JiriCtvrtka** [comment]
Closing due to: https://github.com/percona/pmm/pull/2399

**Pull request closed without merging**
