### PR TITLE
PMM-8566 Node exporter custom password

### PR DESCRIPTION
**Pull request by tshcherban**
PMM-8566

Build: SUBMODULES-2457

- [pmm-admin](https://github.com/percona/pmm-admin/pull/200)
- [pmm-agent](https://github.com/percona/pmm-agent/pull/358)
- [pmm-managed](https://github.com/percona/pmm-managed/pull/1072)

### CODE REVIEW

**Review by BupycHuk — APPROVED** [review]

**Review by YaroslavPodorvanov — APPROVED** [review]

**Review by percona-csalguero — APPROVED** [review]

**Review by JiriCtvrtka — DISMISSED** [review]

**Review by ritbl — APPROVED** [review]
LGTM

**Review by percona-csalguero — DISMISSED** [review]

**Comment by BupycHuk** [comment]
I compiled pmm with Go1.18.1 on my local setup and everything is fine.
using `master` branch isn't a good idea and as we discussed today it's not a good approach to include huge changes into small PR.

**Comment by BupycHuk** [comment]
@ritbl what was the reason to include tool updating into this PR? as far as I see nothing except tooling is changed since my previous approval

**Comment by ritbl** [comment]
@BupycHuk I was trying to fix Tip build, It now generates some potentially useful methods. But I can revert it is wish.

**Comment by BupycHuk** [comment]
Yeah, `tip` is not `required` one and it's better to not use `master` branches for tooling. So, please revert this changes.

**Comment by ritbl** [comment]
@BupycHuk  it's not a good approach to include huge changes into small PR.
all this code is autogenerated, and I believe noone ever review it

**Comment by BupycHuk** [comment]
Yes, but it makes it harder to find what actually was changed.

**Review by ritbl — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Pull request merged**
