### PR TITLE
PMM-4044 Add get network info flag to status request.

### PR DESCRIPTION
**Pull request by BupycHuk**

### CODE REVIEW

**Comment by DexterHD** [comment]
@BupycHuk Basically, I'm not sure we need this flag. What will be wrong if we always know agent status?

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-356/

**Comment by AlekSi** [comment]
@DexterHD It is about sending ping to pmm-managed synchronously, waiting for result, and returning it instead of keeping old result in memory. We don't need latency/drift information in most cases, so we don't ping and wait by default. Please see ticket.

**Comment by AlekSi** [comment]
Please squash once Travis CI is done.

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-356/

**Pull request merged**
