### PR TITLE
PMM-9813 Fix code coverage upload

### PR DESCRIPTION
**Pull request by michal-kralik**
PMM-9813

Build: SUBMODULES-0

This PR fixes code coverage upload.
We can fine-tune thresholds in a separate PR based on discussions and make the check mandatory afterwards.

### CODE REVIEW

**Comment by PavelKhripkov** [comment]
@michal-kralik I fixed 'build' badge in readme in the scope of this PR.

**Review by artemgavrilov — COMMENTED** [review]
Nice, but how it works for monorepo like pmm? We have different codecov results for different parts of this repo, how it's visualized in codecov?

Can we also add code coverage for `admin`, we already have make targets there, we should just to invoke them in CI.

Maybe we also can fix badge for codecov in this PR https://jira.percona.com/browse/PMM-10214 ?

**Comment by michal-kralik** [comment]
@artemgavrilov I updated the config a bit.
With flags and `carryforward` setting this shall work both on admin/agent/managed level as well as project level.

There shall be 4 separate status checks visible on GitHub but I don't see any. Do we maybe have a codecov team YML configuration which prevents that?

**Comment by artemgavrilov** [comment]
I see that for managed codecov upload job failed:
```
 [2022-07-14T08:50:54.785Z] ['info'] -> No token specified or token is empty
[2022-07-14T08:50:54.811Z] ['error'] There was an error running the uploader: Error getting file listing: Error: EACCES: permission denied, scandir '/home/runner/work/pmm/pmm/src/github.com/percona/pmm/managed/services/grafana/fuzzdata'
```

But for admin and agent it seems that upload was sussefull. @BupycHuk  do you know if we have some additional configuration somewhere?

**Comment by michal-kralik** [comment]
@artemgavrilov @BupycHuk This shall be ready for review and merging.
Alex had to re-enable the codecov GitHub app integration for this to work.

I suggest we merge this and monitor.
The piece missing is the codecov comment not showing `managed` but that's because the CI for `managed` fails

**Review by artemgavrilov — APPROVED** [review]

**Review by idoqo — APPROVED** [review]
LGTM

Also, github shows this `github-script` as a submodule - I'm not sure why we need that.

**Review by BupycHuk — APPROVED** [review]

**Comment by idoqo** [comment]
Minor nit: Right now we have about 6 actions with the same "Upload code Coverage" name, something more specific might help when actions fail (or when looking at action results generally).

**Review by idoqo — APPROVED** [review]

**Comment by artemgavrilov** [comment]
> Minor nit: Right now we have about 6 actions with the same "Upload code Coverage" name, something more specific might help when actions fail (or when looking at action results generally).

Agree, but first I want to figure out why we need multiple coverage steps. Will rename jobs in other PR.

**Pull request merged**
