### PR TITLE
Added basic steps (without confirmation)

### PR DESCRIPTION
**Pull request by PaulJacobs-percona**
Left out how to confirm secure cookies as it involves opening dev tools in a browser and searching for a named cookie.

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-575/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-575/

**Comment by puneet0191** [comment]
@PaulJacobs-percona sign the agreement please

**Comment by PaulJacobs-percona** [comment]
@puneet0191 Signed

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-575/

**Review by puneet0191 — APPROVED** [review]

**Pull request merged**
