### PR TITLE
Update descriptors 2.11.0

### PR DESCRIPTION
**Pull request by BupycHuk**

### CODE REVIEW

**Review by AlekSi — APPROVED** [review]
LGTM, will wait for CI

**Comment by BupycHuk** [comment]
@AlekSi everything is ok

**Comment by AlekSi** [comment]
It fails for me locally, checking…

**Review by AlekSi — CHANGES_REQUESTED** [review]
Please check `git diff --text` output on CI. It looks like you did not pull changes or regenerate code before updating descriptors. Or something else is going on. But my local machine and CI both see changes

**Comment by AlekSi** [comment]
image

**Comment by BupycHuk** [comment]
@AlekSi PTAL

**Review by AlekSi — APPROVED** [review]

**Pull request merged**
