### PR TITLE
Pmm 3281 consistent mount point docs

### PR DESCRIPTION
**Pull request by fiowro**

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-263/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-263/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-263/

**Comment by rnovikovP** [comment]
@fiowro  please add this to new  PMM Documentation version

**Pull request closed without merging**
