### PR TITLE
PMM-12741 Percona templated alerts - interval & folder uid

### PR DESCRIPTION
**Pull request by matejkubinec**
PMM-12741

Due to changes in grafana 10.4, usage of folder name instead of folder uid in path would result in a 401.

Support for the evaluation interval was added as it the default flow that grafana currently has for new evaluation groups creation.

Link to the Feature Build: SUBMODULES-3572

Related PRs:
- https://github.com/percona/grafana/pull/714

### CODE REVIEW

**Review by BupycHuk — APPROVED** [review]

**Comment by BupycHuk** [comment]
@matejkubinec please run make format locally to format files

**Comment by ademidoff** [comment]
@BupycHuk I wonder if this PR does not constitute a part of API Breaking changes. If yes, then the base branch needs to be `https://github.com/percona/pmm/tree/v3-api-breaking-changes`.

**Comment by matejkubinec** [comment]
> @BupycHuk I wonder if this PR does not constitute a part of API Breaking changes. If yes, then the base branch needs to be `https://github.com/percona/pmm/tree/v3-api-breaking-changes`.

If the user used the api in the same way as before (without the interval specified), it should work as previously.

**Comment by ademidoff** [comment]
> > @BupycHuk I wonder if this PR does not constitute a part of API Breaking changes. If yes, then the base branch needs to be `https://github.com/percona/pmm/tree/v3-api-breaking-changes`.
> 
> If the user used the api in the same way as before (without the interval specified), it should work as previously.

Right, nevermind :)

**Review by ademidoff — APPROVED** [review]

**Pull request merged**
