### PR TITLE
PMM-2860 and PMM-2904 - improve pmm client and server diagnostics for support

### PR DESCRIPTION
**Pull request by fiowro**

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-232/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-232/

**Comment by michaelcoburn** [comment]
Please review the three troubleshooting bullets and lets add additional detail.  For example, when we ask for netstat and to check connection states:
- [ ] what are good states?
- [ ]  what are bad states? 
- [ ] what exactly do we want to see in a healthy system?  
- [ ] What does an unhealthy system look like? 
show examples

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-232/

**Comment by michaelcoburn** [comment]
Improvements:
* Delete "Troubleshooting Tips" section, up to "about existing network connections." https://github.com/percona/pmm/blob/588e063a679de48488e7904496982a997617fc56/doc/source/faq.rst#troubleshooting-tips

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-232/

**Pull request merged**
