### PR TITLE
[Proposal] PMM-7 Updade year in license headers

### PR DESCRIPTION
**Pull request by artemgavrilov**
PMM-7

### CODE REVIEW

**Comment by ademidoff** [comment]
@artemgavrilov IMO this is not necessary, since the meaning of the year in copyrights is "Since <year> up to now". 

Therefore, the repo files will bear that license until it changes, which is when we should update the year.

**Comment by ademidoff** [comment]
> > @artemgavrilov IMO this is not necessary, since the meaning of the year in copyrights is "Since [year] up to now".
> > Therefore, the repo files will bear that license until it changes, which is when we should update the year.
> 
> Hm, I barely remember that we discussed what to do with the year and I thought that we agreed to update it. I am mistaken and we agreed to not touch year, shouldn't in be 2017 then (year when PMM project started)?

In theory we could put 2017 in there, but I don't see much value added.

Anyway, even if there was a benefit, in my opinion it would just not be worth the effort of:
- touching 750+ files
- dealing with conflicts in v3

**Comment by artemgavrilov** [comment]
@BupycHuk @ademidoff Folks, I'm leaving this to you to decide what to do. I'm ok with any option.

**Comment by ademidoff** [comment]
Closing this for now, will revisit once we stop maintaining v2.

**Pull request closed without merging**
