### PR TITLE
PMM-7 Downgrade go to v1.21

### PR DESCRIPTION
**Pull request by ademidoff**
PMM-7

### CODE REVIEW

**Review by talhabinrizwan — APPROVED** [review]

**Review by JiriCtvrtka — APPROVED** [review]
Is fail on update expected?

**Comment by ademidoff** [comment]
> Is fail on update expected?

No, but it is not related either if we look at `main` branch.

**Review by BupycHuk — APPROVED** [review]
LGTM, have you updated rpmbuild docker image?

**Comment by ademidoff** [comment]
> LGTM, have you updated rpmbuild docker image?

Not yet, but I sure will right after we merge it!

**Pull request merged**
