### PR TITLE
PMM-3336 filters for inventory api

### PR DESCRIPTION
**Pull request by BupycHuk**

### CODE REVIEW

**Comment by AlekSi** [comment]
There are conflicts.
Also please add documentation/comments. `make gen` should check that (if not, that's the bug).

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-260/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-260/

**Comment by BupycHuk** [comment]
@AlekSi `make gen` didn't check it

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-260/

**Comment by AlekSi** [comment]
Let's do only `ListAgentsRequest` filtering by Service ID. Nodes are in the middle of changing ATM.

**Comment by AlekSi** [comment]
Will merge once CI finishes.

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-260/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-260/

**Pull request merged**
