### PR TITLE
PMM-10974 PGSM as default query source for PG.

### PR DESCRIPTION
**Pull request by JiriCtvrtka**
PMM-10974

Link to the Feature Build: SUBMODULES-0

If this PR adds or removes or alters one or more API endpoints, please review and add or update the relevant [API documents](https://github.com/percona/pmm/tree/main/docs/api) as well:

- [ ] API Docs updated

If this PR is related to some other PRs in this or other repositories, please provide links to those PRs:

- Links to related pull requests (optional).

### CODE REVIEW

**Review by percona-csalguero — APPROVED** [review]

**Review by michal-kralik — CHANGES_REQUESTED** [review]
I suggest we document this falls back to `pgstatements`.

**Comment by JiriCtvrtka** [comment]
@michal-kralik What do you mean please?

**Review by rishat-ishbulatov — APPROVED** [review]

**Comment by JiriCtvrtka** [comment]
@michal-kralik We cannot easily verify if PGSM is available or not for now. So without this it cannot simply fallback to pgstatstatements. Right now, customer needs to be sure that PGSM is available in his PG. For Percona distributions its built-in. Its same behaviour for like MySQL.

**Comment by michal-kralik** [comment]
Ok, that's not clear from the ticket.
This means it's a breaking change for some customers. Is it expected?

**Comment by JiriCtvrtka** [comment]
Breaking changes in case of readding service by script for example.

**Review by michal-kralik — APPROVED** [review]

**Pull request merged**
