### PR TITLE
PMM-3763 Adding DockerFile for Sphinx doc build

### PR DESCRIPTION
**Pull request by puneet0191**
Needs to be a specific version of Sphinx 1.6.7, Wget is missing from most of the Docker images, that needs to be installed

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=316) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pmm?pullRequest=316) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pmm?pullRequest=316) it.</sub>

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-316/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-316/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-316/

**Pull request merged**
