### PR TITLE
PMM-2472 (subtask PMM-2650) fix identifying new queries in QAN

### PR DESCRIPTION
**Pull request by fiowro**

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-215/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-215/

**Comment by michaelcoburn** [comment]
LGTM

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-215/

**Pull request merged**
