### PR TITLE
PMM-4459 Disable query example.

### PR DESCRIPTION
**Pull request by askomorokhov**
https://jira.percona.com/browse/PMM-4459

depends on:

https://github.com/percona/pmm/pull/425
https://github.com/percona/pmm-agent/pull/115
https://github.com/percona/pmm-admin/pull/58
https://github.com/percona/qan-app/pull/322

FB: https://github.com/Percona-Lab/pmm-submodules/pull/441

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-425/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-425/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-425/

**Comment by AlekSi** [comment]
Actually, there is nothing controversial :)

**Pull request merged**
