### PR TITLE
Docs moved to pmm-doc

### PR DESCRIPTION
**Pull request by PaulJacobs-percona**
Sphinx/rst migrated to MkDocs/md and copied to 1.x branch of pmm-doc repo.
doc/ dir renamed to .doc until confirmation of content. Then it can be deleted.

### CODE REVIEW

**Review by rnovikovP — APPROVED** [review]

**Review by BupycHuk — APPROVED** [review]

**Comment by BupycHuk** [comment]
I think we should remove these checks which are waiting for status to be reported too

**Comment by PaulJacobs-percona** [comment]
> I think we should remove these checks which are waiting for status to be reported too

Who knows how?

**Comment by atymchuk** [comment]
> > I think we should remove these checks which are waiting for status to be reported too
> 
> Who knows how?

We can't remove them since they are triggering updates for the feature builds when you modify the protobufs, for example.

**Comment by PaulJacobs-percona** [comment]
> > > I think we should remove these checks which are waiting for status to be reported too
> > 
> > 
> > Who knows how?
> 
> We can't remove them since they are triggering updates for the feature builds when you modify the protobufs, for example.

Then it's catch-22. Can't merge until checks finish, which they never will because they depend on docs.

**Pull request merged**
