### PR TITLE
PMM-4471 Change version APIs.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-406/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-406/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-406/

**Comment by AlekSi** [comment]
@BupycHuk PTAL

**Pull request merged**
