### PR TITLE
PMM-4006 Extract ChangeCommonAgentParams.

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-350/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-350/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-350/

**Comment by AlekSi** [comment]
The last commit is technically from the other task but turned out to be tightly coupled with the previous one.

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-350/

**Comment by JNKPercona** [comment]
http://docs-test.cd.percona.com/PR-350/

**Pull request merged**
